### ISSUE TITLE
Error running example of ReLERNN

### ISSUE THREAD

**Issue by tanu06** [kern-lab/ReLERNN#10]
Hello,
After installing all the dependencies and packages when I try to run the example I am getting the below error. 
**ReLERNN/examples$ python2.7 ./example_pipeline.sh**
  File "./example_pipeline.sh", line 14
    ${SIMULATE}
    ^
SyntaxError: invalid syntax
**ReLERNN/examples$  python3.5 ./example_pipeline.sh**
  File "./example_pipeline.sh", line 14
    ${SIMULATE}
    ^
SyntaxError: invalid syntax

**/ReLERNN/examples$ ./example_pipeline.sh**
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/ReLERNN_SIMULATE", line 4, in <module>
    __import__('pkg_resources').run_script('ReLERNN==0.1', 'ReLERNN_SIMULATE')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/EGG-INFO/scripts/ReLERNN_SIMULATE", line 7, in <module>
    from ReLERNN.imports import *
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/ReLERNN/__init__.py", line 4, in <module>
    from ReLERNN.helpers import *
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/ReLERNN/helpers.py", line 184
    out_fp.write(f"pop0,{time_years},{size}\n")
                                             ^
SyntaxError: invalid syntax
./example_pipeline.sh: line 15: --vcf: command not found
./example_pipeline.sh: line 16: --genome: command not found
./example_pipeline.sh: line 17: --mask: command not found
./example_pipeline.sh: line 18: --phased: command not found
./example_pipeline.sh: line 19: --projectDir: command not found
./example_pipeline.sh: line 20: --assumedMu: command not found
./example_pipeline.sh: line 21: --upperRhoThetaRatio: command not found
./example_pipeline.sh: line 22: --nTrain: command not found
./example_pipeline.sh: line 23: --nVali: command not found
./example_pipeline.sh: line 24: --nTest: command not found
./example_pipeline.sh: line 25: --nCPU: command not found

Any help or suggestion is appreciated.
Thank you,
Tanushree

**Comment by andrewkern** [comment]
hi there-- it looks like you are trying to run a bash script with a python interpreter-- that won't work! try it as written in the readme (assuming you have a bash or bash-like) shell

**Comment by tanu06** [comment]
Hello,
Yes, I have tried that and it gives me the following error as I mentioned in the earlier message too.
Yes I am working on Linux server.

ReLERNN/examples$ ./example_pipeline.sh
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/ReLERNN_SIMULATE", line 4, in <module>
    __import__('pkg_resources').run_script('ReLERNN==0.1', 'ReLERNN_SIMULATE')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/EGG-INFO/scripts/ReLERNN_SIMULATE", line 7, in <module>
    from ReLERNN.imports import *
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/ReLERNN/__init__.py", line 4, in <module>
    from ReLERNN.helpers import *
  File "/usr/local/lib/python2.7/dist-packages/ReLERNN-0.1-py2.7.egg/ReLERNN/helpers.py", line 184
    out_fp.write(f"pop0,{time_years},{size}\n")

Thank you,
Tanushree
                                             ^

**Comment by andrewkern** [comment]
It looks like you are using Python 2.7. Our software has not been tested on legacy Python interpreters- I'd suggest moving your install to at least 3.6.

**Comment by tanu06** [comment]
I have multiple versions of python on my server is there anywhere in the script I can mention the version of python.
That was the only reason I was trying to run a bash script with python version.

Thank you for your quick responses.
Tanushree

**Comment by andrewkern** [comment]
just set your environment to use the correct python interpreter. You might even use a virtual environment: https://docs.python-guide.org/dev/virtualenvs/

I'm going to close this issue as the problem seems to be on your side currently. happy to help further in the future.

**Comment by tanu06** [comment]
Sure.

Thank you so much. I really appreciate your quick responses.

Thank You,
Tanushree
