### ISSUE TITLE
Error with ReLERNN example script.

### ISSUE THREAD

**Issue by tanu06** [kern-lab/ReLERNN#11]
Hello,
I was able to install and run the script but in the second step I get this warning and error

***ReLERNN_SIMULATE_POOL.py FINISHED!***

Using TensorFlow backend.
Warning: training data to be treated as if generated by pool-seq
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 2930, 2)           0
_________________________________________________________________
bidirectional_1 (Bidirection (None, 168)               44352
_________________________________________________________________
dense_1 (Dense)              (None, 256)               43264
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 257
=================================================================
Total params: 87,873
Trainable params: 87,873
Non-trainable params: 0
_________________________________________________________________
2019-12-13 14:29:39.255505: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-13 14:29:39.289945: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2497315000 Hz
2019-12-13 14:29:39.293212: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x532a2b0 executing computations on platform Host. Devices:
2019-12-13 14:29:39.293241: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1339, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node bidirectional_1/CudnnRNN}}with these attrs: [dropout=0, seed=87654321, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

         [[bidirectional_1/CudnnRNN]]

During handling of the above exception, another exception occurred:

I don't have GPUs,  is there any other way I can run it.
Any suggestions?
Thank You,
Tanushree

**Comment by jradrion** [comment]
Unfortunately no, ReLERNN requires the use of a CUDA-Enabled NVIDIA GPU.

**Comment by tanu06** [comment]
Okay.
Thank You.
